metro = float(input('Digite um distância em metros: '))
print(f'A distância de {metro}m corresponde a: ')
print(f'{metro/1000}km')
print(f'{metro/100}hm')
print(f'{metro/10}dam')
print(f'{metro*10}dm')
print(f'{metro*100}cm')
print(f'{metro*1000}mm')
